[package]
name = "meshroute"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts = "0.2.23"
bson = { version = "3.1.0", features = ["serde", "serde_with-3"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
rsa = "0.9.9"
libc = "0.2.177"
